[package]
name = "tubereng"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [ 
  "crates/*", 
  "examples/*",
]

[dependencies]
tubereng_winit = { path = "crates/tubereng_winit" }
