[package]
name = "tubereng_asset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
include_dir = "0.7"
