[package]
name = "tubereng_image"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tubereng_asset = { path = "../tubereng_asset" }
image = { version = "0.25", features = ["png", "rayon"] }
